CREATE TABLE IF NOT EXISTS migrations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    last_order INTEGER UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS websites (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    url TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS uptimes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    website_id INTEGER NOT NULL,
    uptime INTEGER NOT NULL,
    response_time INTEGER NOT NULL,
    last_checked TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (website_id) REFERENCES websites (ID)
);